#!/usr/bin/env bash

set -e

cmd=htmlviewer
if ! command $cmd &>/dev/null; then
  cmd="$(basename "$0")"/htmlviewer
  if [[ ! -f "$cmd" ]]; then
    zenity --error --text 'htmlviewer not found'
    exit 1
  fi
fi

ifs="$IFS"
IFS=$'\n'
files=($(zenity --title='Select directories' --file-selection --directory --multiple --separator=$'\n')) || exit 1
IFS="$ifs"

mode=$(zenity --title='Select mode' --list --column='' --text='Default mode' --hide-header normal 'double page' webtoon all) || exit 1
[[ $mode != 'double page' ]] || mode=double

output=${TMPDIR:-/tmp}/htmlviewer.html

"$cmd" -m $mode -- "${files[@]}" > "$output"
xdg-open "$output"
