name: Standalone

on: [push]

jobs:
  standalone:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build standalone
        run: |
          ./htmlviewer -a > index.html
          ./htmlviewer -A > shortcuts.html
          {
            echo -n '<html><head><title>htmlviewer -h</title><meta charset="Utf-8"/><style>
              html{color:#c5c8c6;background:#070a13;}
              .o{color:#ec4d62}
              .v{color:#80e68a}
              .l{color:#6ab9fa}
              .d{color:#999999}
              </style></head><body><pre>'
            ./htmlviewer -h | sed '
              s/&/\&amp;/g
              s/</\&lt;/g
              s/\x1b\[31m/<span class="o">/g
              s/\x1b\[32m/<span class="v">/g
              s/\x1b\[34m/<span class="l">/g
              s/\x1b\[37m/<span class="d">/g
              s/\x1b\[m/<\/span>/g'
            echo '</body></html>'
          } > man.html

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: standalone

      - name: Push changes
        run: |
          mv index.html shortcuts.html man.html standalone/
          cd standalone
          if ! git diff --quiet ; then
            git config --global user.name 'Jonathan Poelen'
            git config --global user.email 'jonathan.poelen@gmail.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git commit -am "update standalone"
            git push
          fi
